
[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production.environment]
NODE_VERSION = "20"

[functions]
node_bundler = "esbuild"

[edge_functions]
included_paths = ["/*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
