import React, { createContext, useContext, useState, ReactNode } from 'react';

interface Photo {
  id: string;
  url: string;
  title: string;
  titleAr: string;
  description: string;
  descriptionAr: string;
  location: string;
  locationAr: string;
  category: string;
  uploadedBy: string;
  uploadDate: string;
  approved: boolean;
  featured: boolean;
}

interface PhotoContextType {
  photos: Photo[];
  uploadedCount: number;
  targetCount: number;
  addPhoto: (
    photo: Omit<Photo, 'id' | 'uploadDate' | 'approved'>,
    approved?: boolean
  ) => void;
  approvePhoto: (id: string) => void;
  deletePhoto: (id: string) => void;
  pendingPhotos: Photo[];
  featuredPhotos: Photo[];
  communityPhotos: Photo[];
  allPhotos: Photo[];
}

const PhotoContext = createContext<PhotoContextType | undefined>(undefined);

export const usePhoto = () => {
  const context = useContext(PhotoContext);
  if (!context) {
    throw new Error('usePhoto must be used within a PhotoProvider');
  }
  return context;
};

interface PhotoProviderProps {
  children: ReactNode;
}

export const PhotoProvider: React.FC<PhotoProviderProps> = ({ children }) => {
  const [photos, setPhotos] = useState<Photo[]>([
    // Real community photos
    {
      id: '1',
      url: '/484134928_122145258254471410_1133353559349890810_n.jpg',
      title: 'Community Gathering',
      titleAr: 'تجمع مجتمعي',
      description: 'A vibrant community event bringing people together',
      descriptionAr: 'فعالية مجتمعية نابضة بالحياة تجمع الناس معاً',
      location: 'Aleppo',
      locationAr: 'حلب',
      category: 'community',
      uploadedBy: 'RCF Team',
      uploadDate: '2024-01-15',
      approved: true,
      featured: true
    },
    {
      id: '2',
      url: '/WhatsApp Image 2025-06-17 at 12.41.33 AM.jpeg',
      title: 'Cultural Festival',
      titleAr: 'مهرجان ثقافي',
      description: 'Celebrating local heritage and traditions',
      descriptionAr: 'الاحتفال بالتراث والتقاليد السورية',
      location: 'Damascus',
      locationAr: 'دمشق',
      category: 'culture',
      uploadedBy: 'Community Member',
      uploadDate: '2024-01-10',
      approved: true,
      featured: true
    },
    {
      id: '3',
      url: '/WhatsApp Image 2025-06-19 at 12.35.09 PM.jpeg',
      title: 'Youth Engagement',
      titleAr: 'مشاركة الشباب',
      description: 'Young people participating in community activities',
      descriptionAr: 'الشباب يشاركون في الأنشطة المجتمعية',
      location: 'Homs',
      locationAr: 'حمص',
      category: 'youth',
      uploadedBy: 'Youth Coordinator',
      uploadDate: '2024-01-08',
      approved: true,
      featured: true
    },
    {
      id: '4',
      url: '/WhatsApp Image 2025-06-19 at 12.35.10 PM.jpeg',
      title: 'Educational Workshop',
      titleAr: 'ورشة تعليمية',
      description: 'Learning and skill development session',
      descriptionAr: 'جلسة تعلم وتطوير المهارات',
      location: 'Latakia',
      locationAr: 'اللاذقية',
      category: 'education',
      uploadedBy: 'Education Team',
      uploadDate: '2024-01-05',
      approved: true,
      featured: true
    },
    // New community photos from attachments
    {
      id: '5',
      url: '/504435580_688802243919719_1259884751197443936_n.jpeg',
      title: 'Community Outreach Program',
      titleAr: 'برنامج التوعية المجتمعية',
      description: 'Volunteers engaging with local community members',
      descriptionAr: 'متطوعون يتفاعلون مع أعضاء المجتمع المحلي',
      location: 'Edmonton, Canada',
      locationAr: 'إدمونتون، كندا',
      category: 'community',
      uploadedBy: 'Rhizome Canada',
      uploadDate: '2024-01-20',
      approved: true,
      featured: true
    },
    {
      id: '6',
      url: '/WhatsApp Image 2025-06-17 at 12.35.13 AM (2).jpeg',
      title: 'Community Support Initiative',
      titleAr: 'مبادرة الدعم المجتمعي',
      description: 'Team members providing assistance and support',
      descriptionAr: 'أعضاء الفريق يقدمون المساعدة والدعم',
      location: 'Local Region',
      locationAr: 'المنطقة',
      category: 'community',
      uploadedBy: 'RCF Team',
      uploadDate: '2024-01-18',
      approved: true,
      featured: true
    },
    {
      id: '7',
      url: '/WhatsApp Image 2025-06-17 at 12.35.14 AM.jpeg',
      title: 'Environmental Project',
      titleAr: 'مشروع بيئي',
      description: 'Community members working on environmental restoration',
      descriptionAr: 'أعضاء المجتمع يعملون على الترميم البيئي',
      location: 'Local Region',
      locationAr: 'المنطقة',
      category: 'community',
      uploadedBy: 'Environmental Team',
      uploadDate: '2024-01-16',
      approved: true,
      featured: true
    },
    {
      id: '8',
      url: '/WhatsApp Image 2025-06-17 at 12.35.14 AM (1).jpeg',
      title: 'Tree Planting Initiative',
      titleAr: 'مبادرة زراعة الأشجار',
      description: 'Volunteers planting trees for community green spaces',
      descriptionAr: 'متطوعون يزرعون الأشجار للمساحات الخضراء المجتمعية',
      location: 'Local Region',
      locationAr: 'المنطقة',
      category: 'community',
      uploadedBy: 'Green Team',
      uploadDate: '2024-01-14',
      approved: true,
      featured: true
    },
    {
      id: '9',
      url: '/WhatsApp Image 2025-06-17 at 12.35.14 AM (2).jpeg',
      title: 'Community Garden Project',
      titleAr: 'مشروع الحديقة المجتمعية',
      description: 'Building sustainable community gardens together',
      descriptionAr: 'بناء حدائق مجتمعية مستدامة معاً',
      location: 'Local Region',
      locationAr: 'المنطقة',
      category: 'community',
      uploadedBy: 'Garden Team',
      uploadDate: '2024-01-12',
      approved: true,
      featured: true
    },
    {
      id: '10',
      url: '/Untitled design (1).jpg',
      title: 'Community Workshop',
      titleAr: 'ورشة مجتمعية',
      description: 'Hands-on training session for local residents',
      descriptionAr: 'جلسة تدريب عملية للسكان المحليين',
      location: 'Toronto, Canada',
      locationAr: 'تورونتو، كندا',
      category: 'community',
      uploadedBy: 'RCF Team',
      uploadDate: '2024-01-22',
      approved: true,
      featured: true
    },
    {
      id: '11',
      url: '/WhatsApp Image 2025-06-17 at 12.39.55 AM (1).jpeg',
      title: 'Arts Event',
      titleAr: 'فعالية فنية',
      description: 'Showcasing creative work from youth members',
      descriptionAr: 'عرض أعمال إبداعية من أعضاء الشباب',
      location: 'Damascus',
      locationAr: 'دمشق',
      category: 'culture',
      uploadedBy: 'Arts Collective',
      uploadDate: '2024-01-21',
      approved: true,
      featured: true
    },
    {
      id: '12',
      url: '/WhatsApp Image 2025-06-19 at 12.35.09 PM copy.jpeg',
      title: 'Food Distribution',
      titleAr: 'توزيع الطعام',
      description: 'Volunteers distributing meals to families',
      descriptionAr: 'متطوعون يوزعون وجبات للأسر',
      location: 'Aleppo',
      locationAr: 'حلب',
      category: 'community',
      uploadedBy: 'Relief Team',
      uploadDate: '2024-01-19',
      approved: true,
      featured: true
    },
    {
      id: '13',
      url: '/WhatsApp Image 2025-06-19 at 12.35.09 PM copy copy.jpeg',
      title: 'Community Meeting',
      titleAr: 'اجتماع مجتمعي',
      description: 'Planning upcoming neighbourhood projects',
      descriptionAr: 'التخطيط لمشاريع الحي القادمة',
      location: 'Edmonton, Canada',
      locationAr: 'إدمونتون، كندا',
      category: 'community',
      uploadedBy: 'Rhizome Canada',
      uploadDate: '2024-01-17',
      approved: true,
      featured: true
    }
    {
      id: "14",
      url: '/20250626_0153_Upscaled Vector Design_remix_01jynkghz8fg4v5w094qqj0epj.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "15",
      url: '/20250629_1822_Gradient Logo Design_remix_01jyz38q10e56bpwt8s4ypzwhj.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "16",
      url: '/20250710_0555_Rhizome Logo Design_remix_01jzt2tem6e8zse9br715pa28n (2).png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "17",
      url: '/5-removebg-preview.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "18",
      url: '/Untitled design (13).png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "19",
      url: '/WhatsApp Image 2025-06-17 at 12.35.12 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "20",
      url: '/WhatsApp Image 2025-07-13 at 6.55.08 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "21",
      url: '/WhatsApp Image 2025-07-13 at 6.55.08 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "22",
      url: '/WhatsApp Image 2025-07-13 at 6.55.09 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "23",
      url: '/WhatsApp Image 2025-07-13 at 6.55.09 AM (2).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "24",
      url: '/WhatsApp Image 2025-07-13 at 6.55.09 AM (3).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "25",
      url: '/WhatsApp Image 2025-07-13 at 6.55.09 AM (4).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "26",
      url: '/WhatsApp Image 2025-07-13 at 6.55.09 AM (5).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "27",
      url: '/WhatsApp Image 2025-07-13 at 6.55.09 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "28",
      url: '/WhatsApp Image 2025-07-13 at 6.55.10 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "29",
      url: '/WhatsApp Image 2025-07-13 at 6.55.10 AM (2).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "30",
      url: '/WhatsApp Image 2025-07-13 at 6.55.10 AM (3).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "31",
      url: '/WhatsApp Image 2025-07-13 at 6.55.10 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "32",
      url: '/WhatsApp Image 2025-07-13 at 6.55.11 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "33",
      url: '/WhatsApp Image 2025-07-13 at 6.55.11 AM (2).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "34",
      url: '/WhatsApp Image 2025-07-13 at 6.55.11 AM (3).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "35",
      url: '/WhatsApp Image 2025-07-13 at 6.55.11 AM (4).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "36",
      url: '/WhatsApp Image 2025-07-13 at 6.55.11 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "37",
      url: '/WhatsApp Image 2025-07-13 at 6.55.12 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "38",
      url: '/WhatsApp Image 2025-07-13 at 6.55.12 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "39",
      url: '/WhatsApp Image 2025-07-13 at 7.01.46 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "40",
      url: '/WhatsApp Image 2025-07-13 at 7.01.46 AM (2).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "41",
      url: '/WhatsApp Image 2025-07-13 at 7.01.46 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "42",
      url: '/WhatsApp Image 2025-07-13 at 7.01.51 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "43",
      url: '/WhatsApp Image 2025-07-13 at 7.01.51 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "44",
      url: '/WhatsApp Image 2025-07-13 at 7.01.52 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "45",
      url: '/WhatsApp Image 2025-07-13 at 7.01.52 AM (2).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "46",
      url: '/WhatsApp Image 2025-07-13 at 7.01.52 AM (3).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "47",
      url: '/WhatsApp Image 2025-07-13 at 7.01.52 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "48",
      url: '/WhatsApp Image 2025-07-13 at 7.01.53 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "49",
      url: '/WhatsApp Image 2025-07-13 at 7.01.53 AM (2).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "50",
      url: '/WhatsApp Image 2025-07-13 at 7.01.53 AM (3).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "51",
      url: '/WhatsApp Image 2025-07-13 at 7.01.53 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "52",
      url: '/WhatsApp Image 2025-07-13 at 7.01.54 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "53",
      url: '/WhatsApp Image 2025-07-13 at 7.01.54 AM (2).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "54",
      url: '/WhatsApp Image 2025-07-13 at 7.01.54 AM (3).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "55",
      url: '/WhatsApp Image 2025-07-13 at 7.01.54 AM (4).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "56",
      url: '/WhatsApp Image 2025-07-13 at 7.01.54 AM (5).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "57",
      url: '/WhatsApp Image 2025-07-13 at 7.01.54 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "58",
      url: '/WhatsApp Image 2025-07-13 at 7.01.55 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "59",
      url: '/WhatsApp Image 2025-07-13 at 7.01.55 AM (2).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "60",
      url: '/WhatsApp Image 2025-07-13 at 7.01.55 AM (3).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "61",
      url: '/WhatsApp Image 2025-07-13 at 7.01.55 AM (4).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "62",
      url: '/WhatsApp Image 2025-07-13 at 7.01.55 AM (5).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "63",
      url: '/WhatsApp Image 2025-07-13 at 7.01.55 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "64",
      url: '/WhatsApp Image 2025-07-13 at 7.01.56 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "65",
      url: '/WhatsApp Image 2025-07-13 at 7.01.56 AM (2).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "66",
      url: '/WhatsApp Image 2025-07-13 at 7.01.56 AM (3).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "67",
      url: '/WhatsApp Image 2025-07-13 at 7.01.56 AM (4).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "68",
      url: '/WhatsApp Image 2025-07-13 at 7.01.56 AM (5).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "69",
      url: '/WhatsApp Image 2025-07-13 at 7.01.56 AM (6).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "70",
      url: '/WhatsApp Image 2025-07-13 at 7.01.56 AM (7).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "71",
      url: '/WhatsApp Image 2025-07-13 at 7.01.56 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "72",
      url: '/assets/1742766100524.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "73",
      url: '/assets/20250626_0153_Upscaled Vector Design_remix_01jynkghz8fg4v5w094qqj0epj.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "74",
      url: '/assets/20250629_1822_Gradient Logo Design_remix_01jyz38q10e56bpwt8s4ypzwhj.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "75",
      url: '/assets/483975544_122145258428471410_3316690589923421989_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "76",
      url: '/assets/484134928_122145258254471410_1133353559349890810_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "77",
      url: '/assets/484211914_122145258338471410_2695303343110288437_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "78",
      url: '/assets/484329714_122145258206471410_5804808056868128839_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "79",
      url: '/assets/484339682_122145258164471410_1115226257337666328_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "80",
      url: '/assets/484374638_122145258116471410_2458659065232253003_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "81",
      url: '/assets/484473407_122145258038471410_6040065715859082511_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "82",
      url: '/assets/484814365_122145258380471410_9061209147408547064_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "83",
      url: '/assets/484902046_122119676636714462_131301557508156433_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "84",
      url: '/assets/485065933_122145258296471410_7882960260343413861_n.jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "85",
      url: '/assets/504435580_688802243919719_1259884751197443936_n.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "86",
      url: '/assets/RCF logo.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "87",
      url: '/assets/Untitled design (1).jpg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "88",
      url: '/assets/WhatsApp Image 2025-06-17 at 12.35.45 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "89",
      url: '/assets/WhatsApp Image 2025-06-17 at 12.39.55 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "90",
      url: '/assets/WhatsApp Image 2025-06-17 at 12.41.32 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "91",
      url: '/assets/WhatsApp Image 2025-06-17 at 12.41.33 AM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "92",
      url: '/assets/WhatsApp Image 2025-06-17 at 12.41.33 AM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "93",
      url: '/assets/WhatsApp Image 2025-06-19 at 12.35.02 PM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "94",
      url: '/assets/WhatsApp Image 2025-06-19 at 12.35.07 PM (1).jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "95",
      url: '/assets/WhatsApp Image 2025-06-19 at 12.35.07 PM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "96",
      url: '/assets/WhatsApp Image 2025-06-19 at 12.35.08 PM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "97",
      url: '/assets/WhatsApp Image 2025-06-19 at 12.35.09 PM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "98",
      url: '/assets/WhatsApp Image 2025-06-19 at 12.35.10 PM.jpeg',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "99",
      url: '/assets/Where Community Takes Root.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "100",
      url: '/assets/logo small.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "101",
      url: '/assets/logo vsmall.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "102",
      url: '/assets/qrcode.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "103",
      url: '/assets/rhw logo.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
    {
      id: "104",
      url: '/slide0007_image015.png',
      title: 'Community Story',
      titleAr: 'قصة المجتمع',
      description: 'Community photo from repository',
      descriptionAr: 'صورة من المستودع',
      location: 'Community',
      locationAr: 'المجتمع',
      category: 'community',
      uploadedBy: 'RCF',
      uploadDate: '2024-01-01',
      approved: true,
      featured: false
    },
  ]);

  // Total number of stories the community aims to collect
  const targetCount = 5000;

  // Count only the photos that have been approved
  const uploadedCount = photos.filter(p => p.approved).length;

  const addPhoto = (
    photoData: Omit<Photo, 'id' | 'uploadDate' | 'approved'>,
    approved = false
  ) => {
    const newPhoto: Photo = {
      ...photoData,
      id: Date.now().toString(),
      uploadDate: new Date().toISOString(),
      approved
    };
    setPhotos(prev => [newPhoto, ...prev]);
  };

  const approvePhoto = (id: string) => {
    setPhotos(prev => prev.map(photo =>
      photo.id === id ? { ...photo, approved: true } : photo
    ));
  };

  const deletePhoto = (id: string) => {
    setPhotos(prev => prev.filter(photo => photo.id !== id));
  };

  const featuredPhotos = photos.filter(photo => photo.featured && photo.approved);
  const communityPhotos = photos.filter(photo => photo.approved);
  const pendingPhotos = photos.filter(photo => !photo.approved);
  
  // Generate additional random photos for the full wall
  const generateRandomPhotos = () => {
    const randomPhotos = [];
    for (let i = 10; i <= 50; i++) {
      randomPhotos.push({
        id: `random-${i}`,
        url: `https://source.unsplash.com/600x600/?syria&sig=${i}`,
        title: `Community Story ${i}`,
        titleAr: `قصة المجتمع ${i}`,
        description: 'A story from our growing community network',
        descriptionAr: 'قصة من شبكة مجتمعنا المتنامية',
        location: 'Various Locations',
        locationAr: 'مواقع متنوعة',
        category: 'community',
        uploadedBy: 'Community Member',
        uploadDate: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
        approved: true,
        featured: false
      });
    }
    return randomPhotos;
  };

  const allPhotos = [...communityPhotos, ...generateRandomPhotos()];

  return (
    <PhotoContext.Provider value={{
      photos,
      uploadedCount,
      targetCount,
      addPhoto,
      approvePhoto,
      deletePhoto,
      pendingPhotos,
      featuredPhotos,
      communityPhotos,
      allPhotos
    }}>
      {children}
    </PhotoContext.Provider>
  );
};
